name: 'Build and push application image'

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd app/ && docker build . -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/pytgweatherbot:latest

    - name: Push docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pytgweatherbot:latest
